CREATE DATABASE QUIZ;

USE teste;

CREATE TABLE QUESTOES(
	IDQUESTAO INT NOT NULL AUTO_INCREMENT,
    QUESTAO VARCHAR(255),
    RESPOSTA CHAR(1),
    ALT_A VARCHAR(255),
    ALT_B VARCHAR(255),
    ALT_C VARCHAR(255),
    ALT_D VARCHAR(255),
    ALT_E VARCHAR(255),
    PRIMARY KEY(IDQUESTAO)
);

SELECT * FROM QUESTOES;

INSERT INTO 
	QUESTOES 
SET 
	QUESTAO = '',
    RESPOSTA = '',
    ALT_A = '',
    ALT_B = '',
    ALT_C = '',
    ALT_D = '',
    ALT_E = '';