CREATE DATABASE QUIZ;

USE QUIZ;

CREATE TABLE QUESTOES(
	IDQUESTAO INT NOT NULL AUTO_INCREMENT,
    	QUESTAO VARCHAR(255),
    	RESPOSTA CHAR(1),
    	ALT_A VARCHAR(255),
    	ALT_B VARCHAR(255),
    	ALT_C VARCHAR(255),
    	ALT_D VARCHAR(255),
    	ALT_E VARCHAR(255),
    	PRIMARY KEY(IDQUESTAO)
);
